name: Linter


on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Run-Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.5.0
